images:
  dlami-x64:
    platform: "linux"
    arch: "x64"
    owner: "898082745236" # AWS
    name: "Deep Learning OSS Nvidia Driver AMI GPU PyTorch 2.3 (Ubuntu 20.04)*"

runners:
  gpu-nvidia-2:
    cpu: [32, 64]
    family: ["g6"]
    spot: false