// Partially based on https://github.com/supranational/sppark/blob/main/rust/build.rs

use std::{
    env,
    ffi::OsStr,
    fs, os,
    path::{Path, PathBuf},
};

use ignore::{DirEntry, WalkBuilder};
use pathdiff::diff_paths;

/// The library name, used for the static library archive and the headers.
/// Should be chosen as to not conflict with other library/header names.
const LIB_NAME: &str = "moongate-core-sys";

/// The name of all include directories involved, used to find and output header files.
const INCLUDE_DIRNAME: &str = "include";

/// The name of the directory to recursively search for sourcefiles in.
const SOURCE_DIRNAME: &str = "cpp";

/// The warning placed in the cbindgen header.
const AUTOGEN_WARNING: &str =
    "/* Automatically generated by `cbindgen`. Not intended for manual editing. */";

fn main() {
    // The name of the header generated by `cbindgen`.
    let cbindgen_hpp = &format!("{LIB_NAME}-cbindgen.hpp");

    // The crate directory.
    let crate_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    // The output directory, where built artifacts should be placed.
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // The include directory of sp1-core-machine-sys.
    let sp1_core_machine_sys_include = env::var("DEP_SP1_CORE_MACHINE_SYS_INCLUDE").unwrap();
    println!("cargo::rustc-link-lib=static=sp1-core-machine-sys");

    // The include directory of sp1-recursion-core-sys.
    let sp1_recursion_core_sys_include = env::var("DEP_SP1_RECURSION_CORE_SYS_INCLUDE").unwrap();
    println!("cargo::rustc-link-lib=static=sp1-recursion-core-sys");

    // The target directory that the cargo invocation is using.
    // Headers are symlinked into `target/include` purely for IDE purposes.
    let target_dir = {
        let mut dir = out_dir.clone();
        loop {
            if dir.ends_with("target") {
                break dir;
            }
            if !dir.pop() {
                panic!("OUT_DIR does not have parent called \"target\": {:?}", out_dir);
            }
        }
    };
    // The directory to read headers from.
    let source_include_dir = crate_dir.join(INCLUDE_DIRNAME);
    // The directory to place headers into.
    let target_include_dir = out_dir.join(INCLUDE_DIRNAME);
    // The directory to place symlinks to headers into. Has the fixed path "target/include".
    let target_include_dir_fixed = target_dir.join(INCLUDE_DIRNAME);

    // The directory to read source files from.
    let source_dir = crate_dir.join(SOURCE_DIRNAME);

    let extension_predicate = |exts: &'static [&str]| {
        move |r: &Result<DirEntry, _>| match r {
            Ok(dir) => {
                dir.file_type().is_some_and(|t| t.is_file())
                    && dir
                        .path()
                        .extension()
                        .and_then(OsStr::to_str)
                        .is_some_and(|ext| exts.contains(&ext))
            }
            Err(_) => true,
        }
    };
    let headers = WalkBuilder::new(&source_include_dir)
        .build()
        .filter(extension_predicate(&["h", "hpp", "cuh"]))
        .collect::<Result<Vec<_>, _>>()
        .unwrap();
    let compilation_units = WalkBuilder::new(source_dir)
        .build()
        .filter(extension_predicate(&["cpp", "cu"]))
        .collect::<Result<Vec<_>, _>>()
        .unwrap();

    // Tell Cargo that if the given file changes, to rerun this build script.
    println!("cargo::rerun-if-changed={INCLUDE_DIRNAME}");
    println!("cargo::rerun-if-changed={SOURCE_DIRNAME}");
    println!("cargo::rerun-if-changed=src");
    println!("cargo::rerun-if-changed=Cargo.toml");

    // Cargo build script metadata, used by dependents' build scripts.
    // The root directory containing the library archive.
    println!("cargo::metadata=root={}", out_dir.to_str().unwrap());
    // The include path defining the library's API.
    println!("cargo::metadata=include={}", target_include_dir.to_str().unwrap());

    // Generate a header containings bindings to the crate.
    match cbindgen::Builder::new()
        .with_pragma_once(true)
        .with_autogen_warning(AUTOGEN_WARNING)
        .with_no_includes()
        .with_sys_include("cstdint")
        .with_parse_deps(true)
        .with_parse_include(&[
            "air",
            "p3-baby-bear",
            "p3-bn254-fr",
            "p3-field",
            "sp1-core-executor",
            "sp1-core-machine",
            "sp1-recursion-core",
            "sp1-stark",
        ])
        .with_namespace("moongate")
        .with_crate(crate_dir)
        .include_item("MatrixViewMutDevice")
        .include_item("CudaStreamHandle")
        .generate()
    {
        Ok(bindings) => {
            // Write the bindings to the target include directory.
            let header_path = target_include_dir.join(cbindgen_hpp);
            if bindings.write_to_file(&header_path) {
                // Symlink the header to the fixed include directory.
                rel_symlink_file(header_path, target_include_dir_fixed.join(cbindgen_hpp));
            }
        }
        Err(cbindgen::Error::ParseSyntaxError { .. }) => {
            // Ignore parse errors so rust-analyzer can run.
        }
        Err(e) => panic!("{:?}", e),
    }

    // Copy the headers to the include directory and symlink them to the fixed include directory.
    for header in headers {
        // Get the path of the header relative to the source include directory.
        let relpath = diff_paths(header.path(), &source_include_dir).unwrap();
        // Let the destination path be the same place relative to the target include directory.
        let dst = target_include_dir.join(&relpath);
        // Create the parent directory if it does not exist.
        if let Some(parent) = dst.parent() {
            fs::create_dir_all(parent).unwrap();
        }
        fs::copy(header.path(), &dst).unwrap();
        rel_symlink_file(dst, target_include_dir_fixed.join(relpath));
    }

    // Now, we actually compile with `nvcc`.
    println!("cargo:rerun-if-changed=../cuda/");
    println!("cargo:rerun-if-changed=../sppark/");
    println!("cargo:rerun-if-env-changed=CXXFLAGS");

    println!("Debug: Watching ../cuda/");
    println!("Debug: Watching ../sppark/");

    let nvcc = which::which("nvcc");

    if let Ok(nvcc) = nvcc {
        let cuda_version =
            std::process::Command::new(nvcc).arg("--version").output().expect("impossible");
        if !cuda_version.status.success() {
            panic!("{:?}", cuda_version);
        }
        let cuda_version = String::from_utf8(cuda_version.stdout).unwrap();
        let x =
            cuda_version.find("release ").expect("can't find \"release X.Y,\" in --version output")
                + 8;
        let y =
            cuda_version[x..].find(',').expect("can't parse \"release X.Y,\" in --version output");
        let v = cuda_version[x..x + y].parse::<f32>().unwrap();
        if v < 12.0 {
            panic!("Unsupported CUDA version {} < 12.0", v);
        }

        // Use the `cc` crate to build the library and statically link it to the crate.
        let mut cc_builder = cc::Build::new();
        cc_builder.cuda(true).flag("-std=c++20").flag("-default-stream=per-thread");
        cc_builder.flag("-Xcompiler").flag("-fopenmp");
        cc_builder.flag("-Xptxas").flag("-suppress-stack-size-warning");
        cc_builder.flag("-lnvToolsExt");
        cc_builder.flag("-ldl");
        cc_builder.flag("--expt-relaxed-constexpr");
        cc_builder.flag("-gencode=arch=compute_86,code=sm_86");
        cc_builder.flag("-gencode=arch=compute_89,code=sm_89");
        cc_builder.flag("-ccbin").flag("g++-11");

        env::set_var("DEP_SPPARK_ROOT", "../sppark");
        if let Some(include) = env::var_os("DEP_SPPARK_ROOT") {
            cc_builder.include(include);
            cc_builder.define("SPPARK", None);
            cc_builder.file("../sppark/rust/src/lib.cpp").file("../sppark/util/all_gpus.cpp");
        }

        cc_builder.define("FEATURE_BABY_BEAR", None);

        cc_builder
            .files(compilation_units.iter().map(DirEntry::path))
            .include(target_include_dir)
            .include(sp1_core_machine_sys_include)
            .include(sp1_recursion_core_sys_include)
            .std("c++20")
            .compile("moongate_cuda");
    }
}

/// Place a relative symlink pointing to `original` at `link`.
fn rel_symlink_file<P, Q>(original: P, link: Q)
where
    P: AsRef<Path>,
    Q: AsRef<Path>,
{
    #[cfg(unix)]
    use os::unix::fs::symlink;
    #[cfg(windows)]
    use os::windows::fs::symlink_file as symlink;

    let target_dir = link.as_ref().parent().unwrap();
    fs::create_dir_all(target_dir).unwrap();
    let _ = fs::remove_file(&link);
    let relpath = diff_paths(original, target_dir).unwrap();
    symlink(relpath, link).unwrap();
}
