#pragma once
#define TOWER_HEIGHT 7
#define INTERPOLATION_TOWER_HEIGHT 2
#define BITS_WIDTH (size_t(1 << TOWER_HEIGHT))
#define INTERPOLATION_BITS_WIDTH (size_t(1 << INTERPOLATION_TOWER_HEIGHT))
#define INTS_PER_VALUE (BITS_WIDTH / 32)

#define BLOCKS 2048u
#define THREADS_PER_BLOCK 32u
#define THREADS (THREADS_PER_BLOCK * BLOCKS)
