use std::{
    iter::{Product, Sum},
    marker::PhantomData,
    ops::{Add, AddAssign, Mul, MulAssign, Neg, Sub, SubAssign},
    sync::Mutex,
};

use lazy_static::lazy_static;
use p3_air::Air;
use p3_air::BaseAir;
use p3_baby_bear::BabyBear;
use p3_field::{extension::BinomialExtensionField, AbstractField};
use p3_field::{AbstractExtensionField, PrimeField32};
use sp1_core::air::SP1_PROOF_NUM_PV_ELTS;
use sp1_core::{
    air::MachineAir,
    stark::{AirOpenedValues, Chip, GenericVerifierConstraintFolder},
};

lazy_static! {
    /// The code generated by the compiler.
    ///
    /// We keep this in a static variable so that we can use native operators.
    pub static ref CUDA_P3_EVAL_CODE: Mutex<Vec<String>> = Mutex::new(Vec::new());

    /// The next available identifier for expressions.
    ///
    /// When we compile expressions like `c = a + b`, allocates an identifier for the output `c`.
    pub static ref CUDA_P3_EVAL_EXPR_CTR: Mutex<usize> = Mutex::new(0);
}

/// The type of the field used for base elements.
type F = BabyBear;

/// The type of the field used for extension elements.
type EF = BinomialExtensionField<F, 4>;

/// A folder which implements all the necessary trait bounds for the constraint folder.
pub type P3EvalFolder<'a> = GenericVerifierConstraintFolder<
    'a,
    F,
    EF,
    SymbolicFolderValue,
    SymbolicFolderValue,
    SymbolicFolderValue,
>;

/// A symbolic value used in the constraint folder which is agnostic to the target backend.
#[derive(Debug, Clone, Copy)]
pub enum SymbolicFolderValue {
    Base(F),
    Extension(EF),
    PreprocessedLocal(usize),
    PreprocessedNext(usize),
    MainLocal(usize),
    MainNext(usize),
    PermutationLocal(usize),
    PermutationNext(usize),
    PermutationChallenge(usize),
    PublicValue(usize),
    IsFirstRow(),
    IsLastRow(),
    IsTransition(),
    Alpha(),
    Accumulator(),
    Intermediate(usize),
}

impl SymbolicFolderValue {
    pub fn id(&self) -> String {
        match self {
            SymbolicFolderValue::Base(value) => format!("bb31_t{{{}}}", value),
            SymbolicFolderValue::Extension(value) => {
                let values: [F; 4] = value.as_base_slice().to_vec().try_into().unwrap();
                format!(
                    "bb31_extension_t((bb31_t[4]){{ bb31_t{{{}}}, bb31_t{{{}}}, bb31_t{{{}}}, bb31_t{{{}}} }})",
                    values[0], values[1], values[2], values[3]
                )
            }
            SymbolicFolderValue::PreprocessedLocal(id) => format!("builder->prepLocal[{}]", id),
            SymbolicFolderValue::PreprocessedNext(id) => format!("builder->prepNext[{}]", id),
            SymbolicFolderValue::MainLocal(id) => format!("builder->mainLocal[{}]", id),
            SymbolicFolderValue::MainNext(id) => format!("builder->mainNext[{}]", id),
            SymbolicFolderValue::PermutationLocal(id) => format!("builder->permLocal[{}]", id),
            SymbolicFolderValue::PermutationNext(id) => format!("builder->permNext[{}]", id),
            SymbolicFolderValue::PermutationChallenge(id) => {
                format!("builder->permChallenge[{}]", id)
            }
            SymbolicFolderValue::PublicValue(id) => format!("builder->publicValues[{}]", id),
            SymbolicFolderValue::IsFirstRow() => "builder->isFirstRow".to_string(),
            SymbolicFolderValue::IsLastRow() => "builder->isLastRow".to_string(),
            SymbolicFolderValue::IsTransition() => "builder->isTransition".to_string(),
            SymbolicFolderValue::Alpha() => "builder->alpha".to_string(),
            SymbolicFolderValue::Accumulator() => "builder->accumulator".to_string(),
            SymbolicFolderValue::Intermediate(id) => format!("tmp{}", id),
        }
    }

    pub fn alloc() -> Self {
        let mut tmp = CUDA_P3_EVAL_EXPR_CTR.lock().unwrap();
        let id = *tmp;
        *tmp += 1;
        SymbolicFolderValue::Intermediate(id)
    }
}

impl Default for SymbolicFolderValue {
    fn default() -> Self {
        SymbolicFolderValue::Base(F::zero())
    }
}

impl AbstractField for SymbolicFolderValue {
    type F = EF;

    fn zero() -> Self {
        let mut code = CUDA_P3_EVAL_CODE.lock().unwrap();
        let output = SymbolicFolderValue::alloc();
        code.push(format!("bb31_extension_t {} = bb31_t{{0}};", output.id()));
        output
    }

    fn one() -> Self {
        let mut code = CUDA_P3_EVAL_CODE.lock().unwrap();
        let output = SymbolicFolderValue::alloc();
        code.push(format!("bb31_extension_t {} = bb31_t{{1}};", output.id()));
        output
    }

    fn two() -> Self {
        let mut code = CUDA_P3_EVAL_CODE.lock().unwrap();
        let output = SymbolicFolderValue::alloc();
        code.push(format!("bb31_extension_t {} = bb31_t{{2}};", output.id()));
        output
    }

    fn neg_one() -> Self {
        let mut code = CUDA_P3_EVAL_CODE.lock().unwrap();
        let output = SymbolicFolderValue::alloc();
        code.push(format!(
            "bb31_extension_t {} = -1 * bb31_t{{1}};",
            output.id()
        ));
        output
    }

    fn from_f(f: Self::F) -> Self {
        SymbolicFolderValue::Extension(f)
    }

    fn from_bool(b: bool) -> Self {
        if b {
            SymbolicFolderValue::Extension(EF::one())
        } else {
            SymbolicFolderValue::Extension(EF::zero())
        }
    }

    fn from_canonical_u8(b: u8) -> Self {
        SymbolicFolderValue::Extension(EF::from_canonical_u8(b))
    }

    fn from_canonical_u16(n: u16) -> Self {
        SymbolicFolderValue::Extension(EF::from_canonical_u16(n))
    }

    fn from_canonical_u32(n: u32) -> Self {
        SymbolicFolderValue::Extension(EF::from_canonical_u32(n))
    }

    fn from_canonical_u64(n: u64) -> Self {
        SymbolicFolderValue::Extension(EF::from_canonical_u64(n))
    }

    fn from_canonical_usize(n: usize) -> Self {
        SymbolicFolderValue::Extension(EF::from_canonical_usize(n))
    }

    fn from_wrapped_u32(n: u32) -> Self {
        SymbolicFolderValue::Extension(EF::from_wrapped_u32(n))
    }

    fn from_wrapped_u64(n: u64) -> Self {
        SymbolicFolderValue::Extension(EF::from_wrapped_u64(n))
    }

    fn generator() -> Self {
        SymbolicFolderValue::Extension(EF::generator())
    }
}

impl From<F> for SymbolicFolderValue {
    fn from(b: F) -> Self {
        SymbolicFolderValue::Base(b)
    }
}

impl From<EF> for SymbolicFolderValue {
    fn from(b: EF) -> Self {
        SymbolicFolderValue::Extension(b)
    }
}

impl Add for SymbolicFolderValue {
    type Output = Self;

    fn add(self, rhs: Self) -> Self::Output {
        let mut code = CUDA_P3_EVAL_CODE.lock().unwrap();
        let output = SymbolicFolderValue::alloc();
        code.push(format!(
            "bb31_extension_t {} = {} + {};",
            output.id(),
            self.id(),
            rhs.id()
        ));
        output
    }
}

impl Add<F> for SymbolicFolderValue {
    type Output = Self;

    fn add(self, rhs: F) -> Self::Output {
        let mut code = CUDA_P3_EVAL_CODE.lock().unwrap();
        let output = SymbolicFolderValue::alloc();
        code.push(format!(
            "bb31_extension_t {} = {} + bb31_t{{{}}};",
            output.id(),
            self.id(),
            rhs
        ));
        output
    }
}

impl AddAssign for SymbolicFolderValue {
    fn add_assign(&mut self, rhs: Self) {
        let mut code = CUDA_P3_EVAL_CODE.lock().unwrap();
        code.push(format!("{} += {};", self.id(), rhs.id()));
    }
}

impl Sub for SymbolicFolderValue {
    type Output = Self;

    fn sub(self, rhs: Self) -> Self::Output {
        let mut code = CUDA_P3_EVAL_CODE.lock().unwrap();
        let output = SymbolicFolderValue::alloc();
        code.push(format!(
            "bb31_extension_t {} = {} - {};",
            output.id(),
            self.id(),
            rhs.id()
        ));
        output
    }
}

impl Sub<F> for SymbolicFolderValue {
    type Output = Self;

    fn sub(self, rhs: F) -> Self::Output {
        let mut code = CUDA_P3_EVAL_CODE.lock().unwrap();
        let output = SymbolicFolderValue::alloc();
        code.push(format!(
            "bb31_extension_t {} = {} - bb31_t{{{}}};",
            output.id(),
            self.id(),
            rhs.as_canonical_u32()
        ));
        output
    }
}

impl SubAssign for SymbolicFolderValue {
    fn sub_assign(&mut self, rhs: Self) {
        let mut code = CUDA_P3_EVAL_CODE.lock().unwrap();
        code.push(format!("{} -= {};", self.id(), rhs.id()));
    }
}

impl Mul for SymbolicFolderValue {
    type Output = Self;

    fn mul(self, rhs: Self) -> Self::Output {
        let mut code = CUDA_P3_EVAL_CODE.lock().unwrap();
        let output = SymbolicFolderValue::alloc();
        code.push(format!(
            "bb31_extension_t {} = {} * {};",
            output.id(),
            self.id(),
            rhs.id()
        ));
        output
    }
}

impl Mul<F> for SymbolicFolderValue {
    type Output = Self;

    fn mul(self, rhs: F) -> Self::Output {
        let mut code = CUDA_P3_EVAL_CODE.lock().unwrap();
        let output = SymbolicFolderValue::alloc();
        code.push(format!(
            "bb31_extension_t {} = {} * bb31_t{{{}}};",
            output.id(),
            self.id(),
            rhs.as_canonical_u32()
        ));
        output
    }
}

impl MulAssign for SymbolicFolderValue {
    fn mul_assign(&mut self, rhs: Self) {
        let mut code = CUDA_P3_EVAL_CODE.lock().unwrap();
        code.push(format!("{} *= {};", self.id(), rhs.id()));
    }
}

impl MulAssign<EF> for SymbolicFolderValue {
    fn mul_assign(&mut self, _rhs: EF) {
        todo!()
    }
}

impl Neg for SymbolicFolderValue {
    type Output = Self;

    fn neg(self) -> Self::Output {
        let mut code = CUDA_P3_EVAL_CODE.lock().unwrap();
        let output = SymbolicFolderValue::alloc();
        code.push(format!(
            "bb31_extension_t {} = -1 * {};",
            output.id(),
            self.id()
        ));
        output
    }
}

impl Sum for SymbolicFolderValue {
    fn sum<I: Iterator<Item = Self>>(iter: I) -> Self {
        iter.fold(SymbolicFolderValue::Base(F::zero()), |acc, val| acc + val)
    }
}

impl Product for SymbolicFolderValue {
    fn product<I: Iterator<Item = Self>>(iter: I) -> Self {
        iter.fold(SymbolicFolderValue::Base(F::one()), |acc, val| acc * val)
    }
}

/// Generates code in CUDA for evaluating the constraint polynomial on the device.
///
/// WARNING: This function is not thread safe.
pub fn codegen_cuda_eval<A>(chip: &Chip<F, A>) -> Vec<String>
where
    A: for<'a> Air<P3EvalFolder<'a>> + MachineAir<F>,
{
    let preprocessed_width = chip.preprocessed_width();
    let width = chip.width();
    let permutation_width = chip.permutation_width();

    let preprocessed = AirOpenedValues {
        local: (0..preprocessed_width)
            .map(SymbolicFolderValue::PreprocessedLocal)
            .collect(),
        next: (0..preprocessed_width)
            .map(SymbolicFolderValue::PreprocessedNext)
            .collect(),
    };
    let main = AirOpenedValues {
        local: (0..width).map(SymbolicFolderValue::MainLocal).collect(),
        next: (0..width).map(SymbolicFolderValue::MainNext).collect(),
    };
    let perm = AirOpenedValues {
        local: (0..permutation_width)
            .map(SymbolicFolderValue::PermutationLocal)
            .collect(),
        next: (0..permutation_width)
            .map(SymbolicFolderValue::PermutationNext)
            .collect(),
    };
    let public_values = (0..SP1_PROOF_NUM_PV_ELTS)
        .map(SymbolicFolderValue::PublicValue)
        .collect::<Vec<_>>();
    let perm_challenges = (0..2)
        .map(SymbolicFolderValue::PermutationChallenge)
        .collect::<Vec<_>>();

    let mut folder = P3EvalFolder {
        preprocessed: preprocessed.view(),
        main: main.view(),
        perm: perm.view(),
        perm_challenges: &perm_challenges,
        cumulative_sum: SymbolicFolderValue::MainLocal(1000),
        public_values: &public_values,
        is_first_row: SymbolicFolderValue::IsFirstRow(),
        is_last_row: SymbolicFolderValue::IsLastRow(),
        is_transition: SymbolicFolderValue::IsTransition(),
        alpha: SymbolicFolderValue::Alpha(),
        accumulator: SymbolicFolderValue::Accumulator(),
        _marker: PhantomData,
    };
    chip.eval(&mut folder);

    let code = CUDA_P3_EVAL_CODE.lock().unwrap().clone();

    CUDA_P3_EVAL_CODE_RESET();
    CUDA_P3_EVAL_EXPR_CTR_RESET();

    code
}

/// Resets [CUDA_P3_EVAL_CODE] for the next compilation.
#[allow(non_snake_case)]
pub fn CUDA_P3_EVAL_CODE_RESET() {
    *CUDA_P3_EVAL_CODE.lock().unwrap() = Vec::new();
}

/// Resets [CUDA_P3_EVAL_EXPR_CTR] for the next compilation.
#[allow(non_snake_case)]
pub fn CUDA_P3_EVAL_EXPR_CTR_RESET() {
    *CUDA_P3_EVAL_EXPR_CTR.lock().unwrap() = 0;
}

#[cfg(test)]
mod tests {
    use sp1_core::air::MachineAir;
    use sp1_core::stark::RiscvAir;
    use sp1_core::utils::BabyBearPoseidon2;

    use crate::codegen_cuda_eval;

    #[test]
    pub fn test_add() {
        let config = BabyBearPoseidon2::default();
        let machine = RiscvAir::machine(config);
        let chips = machine.chips();
        for chip in chips {
            if chip.name() == "AddSub" {
                let code = codegen_cuda_eval(chip);
                println!("{}", code.join("\n"));
                return;
            }
        }
        panic!("no AddSub chip found");
    }
}
