mod operation;
mod symbolic_folder_expr;
mod symbolic_folder_var;

use std::{marker::PhantomData, sync::Mutex};

use lazy_static::lazy_static;
use operation::Operation;
use p3_air::Air;
use p3_air::BaseAir;
use p3_baby_bear::BabyBear;
use p3_field::extension::BinomialExtensionField;
use sp1_core::air::SP1_PROOF_NUM_PV_ELTS;
use sp1_core::{
    air::MachineAir,
    stark::{AirOpenedValues, Chip, GenericVerifierConstraintFolder},
};
use symbolic_folder_expr::SymbolicFolderExpr;
use symbolic_folder_var::SymbolicFolderVar;

lazy_static! {
    /// The code generated by the compiler.
    ///
    /// We keep this in a static variable so that we can use native operators.
    pub static ref CUDA_P3_EVAL_CODE: Mutex<Vec<Operation>> = Mutex::new(Vec::new());

    /// The next available identifier for expressions.
    ///
    /// When we compile expressions like `c = a + b`, allocates an identifier for the output `c`.
    pub static ref CUDA_P3_EVAL_EXPR_CTR: Mutex<usize> = Mutex::new(0);
}

/// The type of the field used for base elements.
pub type F = BabyBear;

/// The type of the field used for extension elements.
pub type EF = BinomialExtensionField<F, 4>;

/// A folder which implements all the necessary trait bounds for the constraint folder.
pub type P3EvalFolder<'a> = GenericVerifierConstraintFolder<
    'a,
    F,
    EF,
    SymbolicFolderVar,
    SymbolicFolderVar,
    SymbolicFolderExpr,
>;

/// Generates code in CUDA for evaluating the constraint polynomial on the device.
///
/// WARNING: This function is not thread safe.
pub fn codegen_cuda_eval<A>(chip: &Chip<F, A>) -> Vec<Operation>
where
    A: for<'a> Air<P3EvalFolder<'a>> + MachineAir<F>,
{
    let preprocessed_width = chip.preprocessed_width();
    let width = chip.width();
    let permutation_width = chip.permutation_width();

    let preprocessed = AirOpenedValues {
        local: (0..preprocessed_width)
            .map(SymbolicFolderVar::preprocessed_local)
            .collect(),
        next: (0..preprocessed_width)
            .map(SymbolicFolderVar::preprocessed_next)
            .collect(),
    };
    let main = AirOpenedValues {
        local: (0..width).map(SymbolicFolderVar::main_local).collect(),
        next: (0..width).map(SymbolicFolderVar::main_next).collect(),
    };
    let perm = AirOpenedValues {
        local: (0..permutation_width)
            .map(SymbolicFolderVar::permutation_local)
            .collect(),
        next: (0..permutation_width)
            .map(SymbolicFolderVar::permutation_next)
            .collect(),
    };
    let public_values = (0..SP1_PROOF_NUM_PV_ELTS)
        .map(SymbolicFolderVar::public_value)
        .collect::<Vec<_>>();
    let perm_challenges = (0..2)
        .map(SymbolicFolderVar::permutation_challenge)
        .collect::<Vec<_>>();

    let mut folder = P3EvalFolder {
        preprocessed: preprocessed.view(),
        main: main.view(),
        perm: perm.view(),
        perm_challenges: &perm_challenges,
        cumulative_sum: SymbolicFolderVar::cumulative_sum(),
        public_values: &public_values,
        is_first_row: SymbolicFolderVar::is_first_row(),
        is_last_row: SymbolicFolderVar::is_last_row(),
        is_transition: SymbolicFolderVar::is_transition(),
        alpha: SymbolicFolderVar::alpha(),
        accumulator: SymbolicFolderVar::accumulator().into(),
        _marker: PhantomData,
    };
    chip.eval(&mut folder);

    let code = CUDA_P3_EVAL_CODE.lock().unwrap().clone();

    CUDA_P3_EVAL_CODE_RESET();
    CUDA_P3_EVAL_EXPR_CTR_RESET();

    code
}

/// Resets [CUDA_P3_EVAL_CODE] for the next compilation.
#[allow(non_snake_case)]
pub fn CUDA_P3_EVAL_CODE_RESET() {
    *CUDA_P3_EVAL_CODE.lock().unwrap() = Vec::new();
}

/// Resets [CUDA_P3_EVAL_EXPR_CTR] for the next compilation.
#[allow(non_snake_case)]
pub fn CUDA_P3_EVAL_EXPR_CTR_RESET() {
    *CUDA_P3_EVAL_EXPR_CTR.lock().unwrap() = 0;
}

#[cfg(test)]
mod tests {
    use sp1_core::air::MachineAir;
    use sp1_core::stark::RiscvAir;
    use sp1_core::utils::BabyBearPoseidon2;

    use crate::codegen_cuda_eval;

    #[test]
    pub fn test_add() {
        println!("test");
        let config = BabyBearPoseidon2::default();
        println!("test2");
        let machine = RiscvAir::machine(config);
        println!("test3");
        let chips = machine.chips();
        for chip in chips {
            println!("chip: {:?}", chip.name());
            if chip.name() == "AddSub" {
                let code = codegen_cuda_eval(chip);
                println!("{:#?}", code);
                println!("{:?}", code.len());
                return;
            }
        }
        panic!("no AddSub chip found");
    }
}
