name: PR

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"
    paths:
      - "air/**"
      - "core/**"
      - "cuda/**"
      - "perf/**"
      - "prover/**"
      - "server/**"
      - "sppark/**"
      - "Cargo.toml"
      - ".github/workflows/**"
      - ".github/runs-on.yml"
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: nvidia-gpu-linux-x64
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup CI
        uses: ./.github/actions/setup
      
      - name: Setup Rust Environment
        shell: bash
        run: |
          . "$HOME/.cargo/env"

      - name: Cargo Check
        run: |
          . "$HOME/.cargo/env"
          RUST_LOG=info cargo check --all-targets --all-features

      - name: Cargo Test
        run: |
          . "$HOME/.cargo/env"
          RUST_LOG=info cargo test --release
 
  lint:
    name: Formatting & Clippy
    runs-on: [runs-on, runner=8cpu-linux-x64, "run-id=${{ github.run_id }}"]
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup CI
        uses: ./.github/actions/setup

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
        env:
          CARGO_INCREMENTAL: 1

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features --all-targets -- -D warnings -A incomplete-features
        env:
          CARGO_INCREMENTAL: 1